export const designTokens = {
  fontSans:
    '"Geist", Inter, -apple-system, BlinkMacSystemFont, "SF Pro Text", system-ui, "Segoe UI", Roboto, sans-serif',
  fontSerif: '"Instrument Serif", Georgia, "Times New Roman", serif',
  fontMono:
    '"SF Mono", "Fira Code", "JetBrains Mono", ui-monospace, SFMono-Regular, Menlo, monospace',
  colorBg: "#f5f5f4",
  colorSurface: "#ffffff",
  colorSurfaceSoft: "#f8f8f6",
  colorSurfaceHover: "#f5f4f1",
  colorBorder: "rgba(0, 0, 0, 0.08)",
  colorBorderStrong: "rgba(0, 0, 0, 0.14)",
  colorText: "#1c1c1a",
  colorTextSecondary: "#44443e",
  colorTextMuted: "#8a8a82",
  colorAccent: "#2563eb",
  colorAccentSoft: "rgba(37, 99, 235, 0.08)",
  colorSuccess: "#16a34a",
  colorWarning: "#d97706",
  colorError: "#b42318",
  shadowCard: "0 10px 30px rgba(15, 23, 42, 0.04)",
  shadowRaised: "0 18px 48px rgba(15, 23, 42, 0.08)",
  spacingXs: "8px",
  spacingSm: "12px",
  spacingMd: "16px",
  spacingLg: "20px",
  spacingXl: "24px",
  radiusCard: "24px",
  radiusInner: "20px",
  panelMaxWidth: "960px"
} as const;

export function buildInlineTokenCss(): string {
  return [
    ":root {",
    `  --font-sans: ${designTokens.fontSans};`,
    `  --font-serif: ${designTokens.fontSerif};`,
    `  --font-mono: ${designTokens.fontMono};`,
    `  --color-bg: ${designTokens.colorBg};`,
    `  --color-surface: ${designTokens.colorSurface};`,
    `  --color-surface-soft: ${designTokens.colorSurfaceSoft};`,
    `  --color-surface-hover: ${designTokens.colorSurfaceHover};`,
    `  --color-border: ${designTokens.colorBorder};`,
    `  --color-border-strong: ${designTokens.colorBorderStrong};`,
    `  --color-text: ${designTokens.colorText};`,
    `  --color-text-secondary: ${designTokens.colorTextSecondary};`,
    `  --color-text-muted: ${designTokens.colorTextMuted};`,
    `  --color-accent: ${designTokens.colorAccent};`,
    `  --color-accent-soft: ${designTokens.colorAccentSoft};`,
    `  --color-success: ${designTokens.colorSuccess};`,
    `  --color-warning: ${designTokens.colorWarning};`,
    `  --color-error: ${designTokens.colorError};`,
    `  --shadow-card: ${designTokens.shadowCard};`,
    `  --shadow-raised: ${designTokens.shadowRaised};`,
    `  --spacing-xs: ${designTokens.spacingXs};`,
    `  --spacing-sm: ${designTokens.spacingSm};`,
    `  --spacing-md: ${designTokens.spacingMd};`,
    `  --spacing-lg: ${designTokens.spacingLg};`,
    `  --spacing-xl: ${designTokens.spacingXl};`,
    `  --radius-card: ${designTokens.radiusCard};`,
    `  --radius-inner: ${designTokens.radiusInner};`,
    `  --panel-max-width: ${designTokens.panelMaxWidth};`,
    "}"
  ].join("\n");
}
